AZURE_AI_FOUNDRY_PROJECT_ENDPOINT="https://pidebrui-aifmcp-resource.services.ai.azure.com/api/projects/pidebrui-aifmcp"
AGENT_TOKEN=
API_VERSION="2025-05-15-preview"

curl -g --request POST \
  --url $AZURE_AI_FOUNDRY_PROJECT_ENDPOINT/assistants?api-version=$API_VERSION \
  -H "Authorization: Bearer $AGENT_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{
    \"instructions\": \"You are a customer support chatbot. Use the tools provided and your knowledge base to best respond to customer queries.\",
    \"tools\": [
          {
              \"type\": \"mcp\",
              \"server_label\": \"LearnMCP\",
              \"server_url\": \"https://learn.microsoft.com/api/mcp\"
          }
      ],
  \"name\": \"my-assistant\",
  \"model\": \"gpt-4o-mini\"
}"

curl --request POST \
  --url $AZURE_AI_FOUNDRY_PROJECT_ENDPOINT/threads?api-version=$API_VERSION \
  -H "Authorization: Bearer $AGENT_TOKEN" \
  -H "Content-Type: application/json" \
  -d ''

curl --request POST \
  --url $AZURE_AI_FOUNDRY_PROJECT_ENDPOINT/threads/thread_dptTedYgXGwtIPG2bZt4HCpG/messages?api-version=$API_VERSION \
  -H "Authorization: Bearer $AGENT_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{
      \"role\": \"user\",
      \"content\": \"how to create an Azure storage account using az cli?\"
    }"

curl --request POST \
  --url $AZURE_AI_FOUNDRY_PROJECT_ENDPOINT/threads/thread_dptTedYgXGwtIPG2bZt4HCpG/runs?api-version=$API_VERSION \
  -H "Authorization: Bearer $AGENT_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{
      \"assistant_id\": \"asst_hNzxXKRde1QebrHbNDqjiRmJ\",
      \"tool_resources\": {
          \"mcp\": [
            {
                \"server_label\": \"LearnMCP\",
                \"require_approval\": \"always\" 
            }
          ]
      }
    }"


curl --request GET \
  --url $AZURE_AI_FOUNDRY_PROJECT_ENDPOINT/threads/thread_dptTedYgXGwtIPG2bZt4HCpG/runs/run_wGsBuxB7vGR4qTyDMDYKRmw7?api-version=$API_VERSION \
  -H "Authorization: Bearer $AGENT_TOKEN"



curl --request POST \
  --url $AZURE_AI_FOUNDRY_PROJECT_ENDPOINT/threads/thread_dptTedYgXGwtIPG2bZt4HCpG/runs/run_wGsBuxB7vGR4qTyDMDYKRmw7/submit_tool_outputs?api-version=$API_VERSION \
  -H "Authorization: Bearer $AGENT_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{
       \"tool_approvals\": [
        {
            \"tool_call_id\": \"call_Hb7iCTjPokJJYdxkBxm8Wpem\",
            \"approve\": true
        }
    ]
}"

curl --request GET \
  --url $AZURE_AI_FOUNDRY_PROJECT_ENDPOINT/threads/thread_dptTedYgXGwtIPG2bZt4HCpG/messages?api-version=$API_VERSION \
  -H "Authorization: Bearer $AGENT_TOKEN"


